baseURL = "https://blog.ferstar.org/"
languageCode = "en-us"
title = "STAY REAL"
theme = "slim"

[params]
  Subtitle = "May the truth be without barriers"
  GithubID = "ferstar"
  # AnalyticsID = "Your Google Analytics tracking code"
  DisqusShortname = "ferstar"
  Summary = false # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  FooterMsg = "Copyright @ferstar 2017, powered by Hugo."
